### ISSUE TITLE
Problem getting API recognized

### ISSUE THREAD

**Issue by gamingoutbrexit** [michaelkirkpatrick/catalog-beer-api#18]
When I enter:
curl -X GET https://api.catalog.beer/brewer/65911cdd-52e6-6305-3420-b9bbf6ea958d -H ‘Accept: application/json' -H ‘Authorization: Basic bccf12ab-1796-4745-9e1a-f71bee61b7ec'
I get a response of:
{"error":true,"error_msg":"Missing API key. Please check that your request includes your API key as the Username using HTTP basic auth and then try again."}curl: (6) Could not resolve host: application
What am I doing wrong?

The verbose version of the response is:
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 66.175.217.212:443...
* Connected to api.catalog.beer (66.175.217.212) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /opt/anaconda3/ssl/cacert.pem
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=plungemasters.com
*  start date: Oct 11 05:22:56 2021 GMT
*  expire date: Jan  9 05:22:55 2022 GMT
*  subjectAltName: host "api.catalog.beer" matched cert's "api.catalog.beer"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
> GET /brewer/65911cdd-52e6-6305-3420-b9bbf6ea958d HTTP/1.1
> Host: api.catalog.beer
> User-Agent: curl/7.71.1
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Date: Sun, 07 Nov 2021 21:51:42 GMT
< Server: Apache/2.4.29 (Ubuntu)
< Set-Cookie: PHPSESSID=logc2c6us1sseqs91blmpke26j; path=/
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< Strict-Transport-Security: max-age=31415926; includeSubDomains; preload
< Content-Length: 156
< Content-Type: application/json
<
* Connection #0 to host api.catalog.beer left intact
{"error":true,"error_msg":"Missing API key. Please check that your request includes your API key as the Username using HTTP basic auth and then try again."}Note: Unnecessary use of -X or --request, GET is already inferred.
* Could not resolve host: application
* Closing connection 1
curl: (6) Could not resolve host: application

**Comment by michaelkirkpatrick** [comment]
Hi @gamingoutbrexit! It's a year later but you still may be interested in an answer to your question. If so, read on!

The issue is that you need to Base64 encode your API Key as part of the cURL request. For example, HTTP Basic Auth requires you to `base64_encode('username:password')`. Recall you'll fill in the `username` with your API Key and leave the `password` field blank. so in your case you would:

```
base64_encode('bccf12ab-1796-4745-9e1a-f71bee61b7ec:')
```

And your cURL request would look something like:

```
curl --location --request GET 'https://api.catalog.beer/brewer'
--header 'Accept: application/json'
--header 'Authorization: Basic YmNjZjEyYWItMTc5Ni00NzQ1LTllMWEtZjcxYmVlNjFiN2VjOg=='
```

A couple notes:

* The brewer_id you were using `65911cdd-52e6-6305-3420-b9bbf6ea958d` no longer exists, so you'll want to update that.
* I've also issued you a new API Key, you can [sign in to your account](https://catalog.beer/account) to view your new API Key (since the key you listed above will be viewable forever here in GitHub).
* I've updated the [API Documentation](https://catalog.beer/api-docs#authentication) with an example in case other people get stuck.

Thanks for your question! I hope you enjoy using the API.

-Michael
